[addon]
name = "Deadly Boss Mods"
version = "1.20.2"
wow_version= "11.0.1"
description = "Boss mods for World of Warcraft"
homepage = "https://deadlybossmods.com"
authors = ["Graham Keenan <graham.keenan@outlook.com>"]
repository = "https://github.com/mysticalos/dbm"
